### ISSUE TITLE
Wikilink autocomplete broken on firefox

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/discourse-wikilinks#10]

**Comment by jessmartin** [comment]
Working in Chrome, but has a broken image next to each post title:
![image](https://user-images.githubusercontent.com/27258/179797470-9f420489-eb84-4ca5-8859-11c3e62fc7b4.png)

**Comment by dvargas92495** [comment]
Im not entirely confident that my changes _should_ be related to the Firefox issue, but it seemed to be resolved on my end when I implemented it. Let me know if Brooke is still seeing issues on the latest version
