### ISSUE TITLE
Backlinks are attaching to multiple places, including in comments

### ISSUE THREAD

**Issue by bmann** [dvargas92495/discourse-wikilinks#8]
There are weird visual elements and rendering aspects around the way backlinks are being inserted:

![Screen Shot 2022-07-06 at 2 15 45 PM](https://user-images.githubusercontent.com/280420/177644858-7d0039ea-f944-4ae5-b2e7-a047f8f30780.png)

I'm hovering over the action items on a comment, and additionally backlinks pop into place / disappear again.

As well, every reply in this thread has its own backlinks.

Finally, this post and the replies don't contain any wikilinks. This is a brand new post, and it doesn't actually HAVE any backlinks to it.

**Comment by bmann** [comment]
Here’s another example 

![54302C59-3680-4C8E-9782-5D5CD0BB047A](https://user-images.githubusercontent.com/280420/177870945-78ed6d44-b602-4840-adff-300d5a83e0a9.jpeg)

This is a brand new public post. It has a tag in common with the post that is being added as a backlink — but this shouldn’t be added. 

That being said — I think it’s super interesting to be able to tweak the “not linked but related” algo — but it shouldn’t be in the same spot as the “real” backlinks. 

You won’t be able to see the backlink because it’s a private post, but here’s the Public post https://talk.fission.codes/t/zkp-learning-resources/3003

**Comment by dvargas92495** [comment]
The bug mentioned in the title should now be fixed - however I wasn't able to replicate: 

> Finally, this post and the replies don't contain any wikilinks. This is a brand new post, and it doesn't actually HAVE any backlinks to it.

Could we link the screenshotted post?

**Comment by jessmartin** [comment]
> Could we link the screenshotted post?

Unfortunately, it's Fission internal. We're installing the new version (0.3.1) and I'll test it out and let you know!
